on:
    workflow_call:
        inputs:
            registry_host:
                required: true
                type: string
            registry_username:
                required: true
                type: string
            image_name:
                required: true
                type: string
            image_digest:
                required: true
                type: string
                description: 'Docker image digest to tag'
            image_tag:
                required: false
                type: string
                description: 'Tag to apply to the image (optional - if not set, only latest_tag is applied)'
                default: ''
            latest_tag:
                required: false
                type: string
                description: 'Latest tag to apply (default: latest)'
                default: 'latest'
        secrets:
            registry_password:
                required: true

jobs:
    deploy-docker:
        name: Deploy - Docker
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ inputs.registry_host }}
                  username: ${{ inputs.registry_username }}
                  password: ${{ secrets.registry_password }}

            - name: Create and push version tag
              if: ${{ inputs.image_tag != '' }}
              run: |
                  docker buildx imagetools create \
                    --tag ${{ inputs.registry_host }}/${{ inputs.image_name }}:${{ inputs.image_tag }} \
                    ${{ inputs.registry_host }}/${{ inputs.image_name }}@${{ inputs.image_digest }}

            - name: Create and push latest tag
              run: |
                  docker buildx imagetools create \
                    --tag ${{ inputs.registry_host }}/${{ inputs.image_name }}:${{ inputs.latest_tag }} \
                    ${{ inputs.registry_host }}/${{ inputs.image_name }}@${{ inputs.image_digest }}
