on:
    workflow_call:
        inputs:
            node_version:
                type: string
                description: 'Node.js version to use'
                required: false
        secrets: {}

jobs:
    test-lint:
        name: Test - Lint
        runs-on: ['runners-ditiac-prod']
        continue-on-error: true
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ inputs.node_version }}

            - name: Install PNPM
              run: |
                  npm install -g pnpm
                  pnpm config set store-dir ${{ github.workspace }}/.pnpm-store

            - name: Setup Cache for pnpm
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ github.workspace }}/.pnpm-store
                      ${{ github.workspace }}/node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Run lint checks
              run: pnpm run lint
